name: Deploy Discord Bot

on:
  push:
    branches:
      - master  # Измените, если ваша основная ветка отличается
  schedule:
    - cron: '59 */6 * * *'  # Запуск каждую 6-ю неделю за 59 минут
    - cron: '0 */6 * * *'   # Запуск каждую 6-ю неделю на 0 минуте

jobs:
  run_bot:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Create unique database file
      run: |
        mkdir -p database  # Создание директории, если её нет
        FILENAME="file_$(date +%Y%m%d%H%M%S).db"  # Создание уникального имени файла с меткой времени
        touch database/$FILENAME  # Создание файла с уникальным именем
        echo "Database file created: $FILENAME"  # Вывод имени созданного файла

    - name: Start Bot
      run: |
        echo "Starting bot..."
        node .  # Запуск бота, но не в фоновом режиме
      env:
        TOKEN: ${{ secrets.TOKEN }}

  create_new_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'  # Проверка, что работа запущена по расписанию
    
    steps:
    - name: Notify creation of new job
      run: |
        echo "Creating a new job every 5 hours and 59 minutes..."
        # Здесь можно добавить команды для выполнения новых задач
