name: Deploy Discord Bot

on:
  schedule:
    - cron: '*/120 * * * *'  # Запуск каждые 2 часа

jobs:
  run_and_check_bot:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Start Bot
      run: |
        echo "Starting bot..."
        node app.js &  # Запуск бота в фоновом режиме
        echo "Bot started with process ID $!"
        sleep 7200  # Подождать 2 часа (7200 секунд)
        echo "Stopping bot..."
        kill $!  # Остановить бот

    - name: Check for new jobs
      run: |
        echo "Executing additional tasks every 20 minutes..."
        # Здесь можно добавить дополнительные команды
      if: ${{ (github.event.schedule ) }}  #0 Убедитесь, что выполняете дополнительные задачи только по расписанию

    env:
      TOKEN: ${{ secrets.TOKEN }}
      HOST: ${{ secrets.DB_HOST }}
      USER: ${{ secrets.DB_USER }}
      PASS: ${{ secrets.DB_PASS }}
      DB: ${{ secrets.DB_NAME }}
