name: Deploy Discord Bot

on:
  push:
    branches:
      - master  # change if your default branch is different
  schedule:
    - cron: '*/20 * * * *'  # Check for updates every 20 minutes

jobs:
  run_bot:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Create unique database file
      run: |
        mkdir -p database  # Создание директории, если её нет
        FILENAME="file_$(date +%Y%m%d%H%M%S).db"  # Создание уникального имени файла с меткой времени
        touch database/$FILENAME  # Создание файла с уникальным именем
        echo "Database file created: $FILENAME"  # Вывод имени созданного файла

    - name: Start Bot
      run: |
        echo "Starting bot..."
        node .  # Запуск бота в фоновом режиме
      env:
        TOKEN: ${{ secrets.TOKEN }}

  check_for_new_jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Execute additional tasks
      run: |
        echo "Executing additional tasks every 20 minutes..."
        # Here you can add additional commands
