name: Run Discord Bot

on:
  push:
    branches:
      - master

jobs:
  run_bot:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Устанавливаем тайм-аут на 120 минут

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Замените на вашу версию Node.js

    - name: Install dependencies
      run: npm install

    - name: Start Bot
      run: |
        echo "Starting bot..."
        node .  # Запускаем бота
      env:
        TOKEN: ${{ secrets.TOKEN }}  # Убедитесь, что токен хранится в секрете

  background_job:
    runs-on: ubuntu-latest
    needs: run_bot  # Ожидает завершения run_bot
    timeout-minutes: 120  # Устанавливаем тайм-аут для фонового задания

    steps:
    - name: Background Task
      run: |
        echo "Running background tasks while the bot is active..."
        # Здесь можете добавить команды для фоновых задач

  stop_bot:
    runs-on: ubuntu-latest
    needs: background_job  # Ожидает завершения background_job
    if: always()  # Выполняется всегда после background_job

    steps:
    - name: Stop Bot
      run: |
        echo "Stopping bot after background tasks..."
        # Здесь можно добавить команды для отключения бота, если это нужно
